provider:
  name: faas
  gateway: http://localhost:8080

functions:
  youtubedl:
    skip_build: true
    image: alexellis2/faas-youtubedl:latest
    fprocess: "sh ./entry.sh"
    environment:
      read_timeout: 120   # 2 mins
      write_timeout: 120
      write_debug: false
      read_debug: false

  gifit:
    skip_build: true
    image: alexellis/gif-maker:latest
    fprocess: "sh ./entry.sh"
    environment:
      read_timeout: 120   # 2 mins
      write_timeout: 120
      write_debug: false
      read_debug: false
  
